services:
  - type: web
    name: varad-hospital
    env: node
    rootDir: VARAD-HOSPITAL   # point to the right folder
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
