services:
  - type: web
    name: varad-hospital
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
